//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetPublisher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<eventHub_ConnectionString>")]
        public string eventHub_ConnectionString {
            get {
                return ((string)(this["eventHub_ConnectionString"]));
            }
            set {
                this["eventHub_ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<Access_Token>")]
        public string Access_Token {
            get {
                return ((string)(this["Access_Token"]));
            }
            set {
                this["Access_Token"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<Access_Token_Secret>")]
        public string Access_Token_Secret {
            get {
                return ((string)(this["Access_Token_Secret"]));
            }
            set {
                this["Access_Token_Secret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<Consumer_Key>")]
        public string Consumer_Key {
            get {
                return ((string)(this["Consumer_Key"]));
            }
            set {
                this["Consumer_Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<Consumer_Secret>")]
        public string Consumer_Secret {
            get {
                return ((string)(this["Consumer_Secret"]));
            }
            set {
                this["Consumer_Secret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<hashtag_filter>")]
        public string hashtag_filter {
            get {
                return ((string)(this["hashtag_filter"]));
            }
            set {
                this["hashtag_filter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<eventHub_hubname>")]
        public string eventHub_hubname {
            get {
                return ((string)(this["eventHub_hubname"]));
            }
            set {
                this["eventHub_hubname"] = value;
            }
        }
    }
}
